Completed css-grid-classes.
youssefnajjarine/m1-321-code-solutions pull request #18
Opened 2021-03-19 17:45 UTC by youssefnajjarine

![image](https://user-images.githubusercontent.com/71291742/111821739-3af1c480-88a0-11eb-87ee-4aaef672c3ec.png)

2021-03-19 18:29 UTC, Zhiwutian requested changes
Hey Youssef, decent initial implementation on this. But there are a few things which need to be adjusted:
1. The exercise is supposed to be completed with grid classes as described in the instructions. 
2. Grid classes means using a container element, and a series of rows with columns that are percentage based. 
3. Please refactor this exercise with that in mind, if you have questions as you are working on it, please reach out!

2021-03-19 23:01 UTC, Zhiwutian requested changes
Moving in the right direction! A few more updates are noted.

2021-03-19 23:01 UTC, BrettAlbright commented on css-grid-classes/index.html
> +      <div class="column-one-third">
you want to have 3 `column-one-third` classes in this row, one for link, one for the text, and one for yoshi and each should be 1/3 width of the whole row in percentage

2021-03-19 23:01 UTC, BrettAlbright commented on css-grid-classes/index.html
> +          <div class="row2">
There should only be a single `row` class that is used for each row

2021-03-19 23:01 UTC, BrettAlbright commented on css-grid-classes/index.html
> +            <div class="column-one"><img src="images/kirby.png"/></div>
each of these elements should have the same column class set to be 1/4 the total width as a percentage.

2021-03-19 23:01 UTC, BrettAlbright commented on css-grid-classes/index.html
> +          <div class="row3">
should be the single row class

2021-03-19 23:01 UTC, BrettAlbright commented on css-grid-classes/index.html
> +            <div class="column-one">
should be two columns in this row, one that is 1/3 the length for the text, and one that is 2/3 the length for the image

2021-03-19 23:01 UTC, Zhiwutian commented on css-grid-classes/index.html
> +    <div class="row4">
single row class

2021-03-19 23:01 UTC, Zhiwutian commented on css-grid-classes/index.html
> +      <div class="column-one">
these column widths should be the same wisth as the row above

2021-03-19 23:01 UTC, Zhiwutian commented on css-grid-classes/styles.css
> +.column-one-third,
remember, there should be only one `row` class set to display flex. And all of the column classes need to be given proper width values.

2021-03-20 18:08 UTC, Zhiwutian approved these changes
👍

2021-03-20 18:11 UTC, merged